paths:
  neut_file: "/home/hep/tlt26/RW_Snakemake/NEUT_file/T2KND_FHC_numu_H2O_NEUT562_1M_0000_NUISFLAT.root"
  genie_file: "/home/hep/tlt26/RW_Snakemake/GENIE_file/T2KND_FHC_numu_H2O_GENIEv3_G18_10b_00_000_1M_0000_NUISFLAT.root"

analysis:
  modes: 
    - 1

  neutrino_PDG: 14
  train_percentage: 0.4
  val_percentage: 0.4

features:
  parameters_interest:
    - Enu_true
    - Q2
    - W
    - y
    - Mode
    - N_n
    - K_n
    - N_p
    - K_p
    - N_pi0
    - K_pi0
    - N_pip
    - K_pip
    - N_pim
    - K_pim
  
  binning_file: "/home/hep/tlt26/RW_Snakemake/binnings.json"


models:
  model_list:
    - XGB
  
  number_model_hyperparameters_sets:
    binning: 24
    NN: 240
    GBR: 270
    XGB : 150
    

dimensions:
  dim: 15

output:
  tag: "15D_mode1_novaparam"