paths:
  neut_file: "/home/hep/tlt26/RW_Snakemake/NEUT_file/T2KND_FHC_numu_H2O_NEUT562_1M_0000_NUISFLAT.root"
  genie_file: "/home/hep/tlt26/RW_Snakemake/GENIE_file/T2KND_FHC_numu_H2O_GENIEv3_G18_10b_00_000_1M_0000_NUISFLAT.root"

analysis:
  modes: 
    - 1
    

  modes_v2:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    

  neutrino_PDG: 14
  train_percentage: 0.4
  val_percentage: 0.4

features:
  parameters_interest:
    - Enu_true
    - ELep
    - CosLep
    - W
    - Eav
  
  binning_file: "/home/hep/tlt26/RW_Snakemake/binnings.json"


models:
  model_list:
    - XGB
  
  number_model_hyperparameters_sets:
    binning: 24
    NN: 240
    GBR: 270
    XGB : 150
    

dimensions:
  dim: 5

output:
  tag: "5D_Mode1_early_stopping"