paths:
  neut_file: "/home/hep/tlt26/RW_Snakemake/NEUT_file/T2KND_FHC_numu_H2O_NEUT562_1M_0000_NUISFLAT.root"
  genie_file: "/home/hep/tlt26/RW_Snakemake/GENIE_file/T2KND_FHC_numu_H2O_GENIEv3_G18_10b_00_000_1M_0000_NUISFLAT.root"

analysis:
  modes: 
    - 1
    # - 2
    # - 11
    # - 12
    # - 13
    # - 16
    # - 17
    # - 21
    # - 22
    # - 23
    # - 26
    # - 31
    # - 32
    # - 33
    # - 34
    # - 36
    # - 38
    # - 39
    # - 41
    # - 42
    # - 43
    # - 44
    # - 45
    # - 46
    # - 51
    # - 52

    #choose in 1, 2, 11, 12, 13, 16, 17, 21, 22, 23, 26, 31, 32, 33, 34, 36, 38, 39, 41, 42, 43, 44, 45, 46, 51 and 52

    

  modes_v2:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    
  #choose in 0, 1, 2, 3, 4, 5, 6 and 7 (0 for CC0pi, 1 for CC1pipm, 2 for CC1pi0, 3 for CCNpi, 4 for CCOther, 5 for the rest, 6 for CCgamma, 7 for CCOther_QE)


  neutrino_PDG: 14
  train_percentage: 0.4
  val_percentage: 0.4

features:
  parameters_interest:
    - Enu_true
    - Plep
    - CosLep
    
  
  binning_file: "/home/hep/tlt26/RW_Snakemake/binnings.json"


models:
  model_list:
    - binning
    - NN
    - GBR
    - XGB
  
  number_model_hyperparameters_sets:
    binning: 24
    NN: 240
    GBR: 270
    XGB : 96
    

dimensions:
  dim: 3_custom
  # In case of 3 or 8 dimensions, add a 'custom' tag to rule out the degeneracy with the regular 3D and 8D cases (always computed for metrics).

output:
  tag: "3D_CCQE_PLep"